---
# Extend default settings for all of my personal repositories defined in .github/settings.yml
_extends: .github:common-settings.yaml

repository:
  name: gala-chain-code
  description: Experiments with GalaChain

  topics: >-
    galachain,
    gala-chain,
    hyperledger,
    fabric,
    chaincode,
    blockchain

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      required_pull_request_reviews: null
      restrictions: null
      required_linear_history: true
