---
name: main

"on":
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main, "renovate/**"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: "bash -Eeuxo pipefail {0}"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run test

  test-e2e:
    name: Test E2E
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: |
          npm run network:start & # Run network in background and wait for it to start
          sleep 120
          npm run test:e2e

          MAX_BLOCK_INDEX=$(curl --location 'http://localhost:3010/product-channel/blocks' --header 'Content-Type: application/json' | jq '.info.fromBlock')
          if [ $MAX_BLOCK_INDEX -lt 56]; then
            echo "The number of blocks is less than 56, exiting."
            exit 1
          fi
          echo "There are at $MAX_BLOCK_INDEX blocks after the tests."
          npm run network:prune # Stop the network
